spring:
  application:
    name: history-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_DB_USERNAME}
      password: ${MONGODB_DB_PASSWORD}
azure:
  eventhub:
    connection-string: ${EVENTHUB_CONNECTION_STRING}
    number-encrypt:
      name: ${EVENTHUB_ENCRYPT_NUM_REQ}
    message-send:
      name: ${EVENTHUB_MESSAGE_SEND_REQ}
    message-result:
      name: ${EVENTHUB_MESSAGE_RESULT_RES}
    consumer-group:
      message: message-consumer-group
      history: history-consumer-group
server:
  port: 8083
