spring:
  application:
    name: message-service
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    
server:
  port: 8082

encryption:
  key: ${ENCRYPTION_KEY}

azure:
  eventhub:
    connection-string: ${EVENTHUB_CONNECTION_STRING}
    number-encrypt:
      name: ${EVENTHUB_ENCRYPT_NUM_REQ}
    message-send:
      name: ${EVENTHUB_MESSAGE_SEND_REQ}
    message-result:
      name: ${EVENTHUB_MESSAGE_RESULT_RES}
    consumer-group:
      message: message-consumer-group
      history: history-consumer-group
