spring:
  application:
    name: message-service
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    
server:
  port: 8082

azure:
  eventhub:
    connection-string: ${EVENTHUB_CONNECTION_STRING}
    name: ${EVENTHUB_NAME}

encryption:
  key: ${ENCRYPTION_KEY}
