spring:
  application:
    name: message-service
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100  # 최대 풀 크기
      minimum-idle: 10       # 최소 유휴 연결 수
      idle-timeout: 30000    # 유휴 연결 타임아웃 (밀리초)
      max-lifetime: 300000
      connection-timeout: 30000  # 커넥션 획득 대기 시간 (밀리초)
      keepalive-time: 120000      # 2분
      validation-timeout: 5000    # 5초
      leak-detection-threshold: 60000  # 1분
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
server:
  port: 8082
  tomcat:
    max-swallow-size: -1



encryption:
  key: ${ENCRYPTION_KEY}

azure:
  eventhub:
    enabled: true
    connection-string: ${EVENTHUB_CONNECTION_STRING}
    number-encrypt:
      name: ${EVENTHUB_ENCRYPT_NUM_REQ}
    message-send:
      name: ${EVENTHUB_MESSAGE_SEND_REQ}
    message-result:
      name: ${EVENTHUB_MESSAGE_RESULT_RES}
    consumer-group:
      message: message-consumer-group
      history: history-consumer-group

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      app: ${spring.application.name}
      instance: ${HOSTNAME:localhost}:${server.port}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s