server:
  port: 9081    # 추가된 부분

spring:
  datasource:
    url: ${MESSAGE_DB_URL}
    username: ${MESSAGE_DB_USERNAME}
    password: ${MESSAGE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eventhub:
  connectionString: ${EVENTHUB_CONNECTION_STRING}

rcs:
  successRate: 99

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rcs.external: INFO