spring:
  application:
    name: history-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_DB_USERNAME}:${MONGODB_DB_PASSWORD}@${MONGODB_URI}/${MONGODB_DATABASE}?retryWrites=true&w=majority
      username: ${MONGODB_DB_USERNAME}
      password: ${MONGODB_DB_PASSWORD}
      database: ${MONGODB_DATABASE}
azure:
  eventhub:
    enabled: true
    connection-string: ${EVENTHUB_CONNECTION_STRING}
    number-encrypt:
      name: ${EVENTHUB_ENCRYPT_NUM_REQ}
    message-send:
      name: ${EVENTHUB_MESSAGE_SEND_REQ}
    message-result:
      name: ${EVENTHUB_MESSAGE_RESULT_RES}
    consumer-group:
      message: message-consumer-group
      history: history-consumer-group
server:
  port: 8083

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      app: ${spring.application.name}
      instance: ${HOSTNAME:localhost}:${server.port}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s