spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_DB_URL}
#    url : jdbc:postgresql://localhost:5432/postgres
    username: ${AUTH_DB_USERNAME}
#    username : postgres
    password: ${AUTH_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ktds.rcsp: DEBUG

server:
  port: 8081

jwt:
  secret: temporary_secret_key_for_development
  expiration: 1800000

eventhub:
  enabled: false
